sudo: false
language: ruby
rvm:
  - 2.5.0
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - bundle exec rspec spec
before_install: gem install bundler -v 1.17.3
deploy:
  provider: rubygems
  api_key:
    secure: your_secure_secret
  gem: ledgerizer
  on:
    tags: true
    repo: platanus/ledgerizer
