development: &default
  adapter: postgresql
  database: ledgerizer_development
  encoding: utf8
  host: <%= ENV["POSTGRESQL_HOST"] || "127.0.0.1" %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>
  username: <%= ENV["POSTGRESQL_USER"] %>
  min_messages: warning
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  reaping_frequency: <%= Integer(ENV.fetch("DB_REAPING_FREQUENCY", 10)) %>
  timeout: 5000

test:
  <<: *default
  database: ledgerizer_test

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url: <%= ENV.fetch("DATABASE_URL", "") %>
